# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: push
  
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Docker compose up
              run: docker-compose up -d

            - name: docker ps
              run: docker ps

            - name: connect to container
              run: curl http://localhost:5432