# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: push
  
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            
            - name: Who am i
              run: whoami
            - name: Install pg_isready
              run: sudo apt-get install postgresql-client-9.6

            - name: Docker compose up
              run: docker-compose up -d

            - name: docker ps
              run: docker ps

            - name: connect to container
              run: |
                while ! pg_isready -h localhost -p 5432 -U docker
                do
                    echo "$(date) - waiting for database to start"
                    sleep 10
                done
